In [1]:
import pandas as pd
from scipy.spatial import distance_matrix

In [2]:
data = [[1, 4], [2, 5], [3, 6]]
df = pd.DataFrame(data, columns = ['a', 'b'])
df

   a  b
0  1  4
1  2  5
2  3  6

In [3]:
pd.DataFrame(distance_matrix(df.values, df.values))

          0         1         2
0  0.000000  1.414214  2.828427
1  1.414214  0.000000  1.414214
2  2.828427  1.414214  0.000000