In [1]:
import pandas as pd
import numpy as np
import math
from scipy import stats
import scipy
import statsmodels.api as sm
from statsmodels.formula.api import ols
from matplotlib import pyplot as plt

In [2]:
data = pd.read_excel('oneway.xlsx')

In [3]:
data

   Black Board   Case Presentation    PPT
0             4                    2     2
1             3                    4     1
2             2                    6     3

In [4]:
print(data.columns)

Index(['Black Board ', 'Case Presentation  ', 'PPT '], dtype='object')

In [5]:
data.columns = data.columns.str.strip()
print(data.columns)

Index(['Black Board', 'Case Presentation', 'PPT'], dtype='object')

In [6]:
data_new = pd.melt(
    data.reset_index(),
    id_vars=['index'],
    value_vars=['Black Board', 'Case Presentation', 'PPT']
)

data_new.columns = ['index', 'Treatments', 'value']

In [7]:
data_new

   index         Treatments  value
0      0        Black Board      4
1      1        Black Board      3
2      2        Black Board      2
3      0  Case Presentation      2
4      1  Case Presentation      4
5      2  Case Presentation      6
6      0                PPT      2
7      1                PPT      1
8      2                PPT      3

In [8]:
model = ols('value ~ C(Treatments)', data=data_new).fit()

In [9]:
anova_table = sm.stats.anova_lm(model, typ=1)

In [10]:
anova_table

                df  sum_sq  mean_sq    F    PR(>F)
C(Treatments)  2.0     6.0      3.0  1.5  0.296296
Residual       6.0    12.0      2.0  NaN       NaN