In [1]:
import pandas as pd
import scipy.stats as stats
from statsmodels.stats.multicomp import MultiComparison

In [2]:
f_critical = stats.f.ppf(1 - 0.05, dfn=4, dfd=20)
print(f_critical)

2.8660814020156584

In [3]:
df3 = pd.read_excel(r"cotton weight.xlsx")
df3.head()

   cotwt.15  cotwt.20  cotwt.25  cotwt.30  cotwt.35
0         7        12        14        19         7
1         7        17        18        25        10
2        15        12        18        22        11
3        11        18        19        19        15
4         9        18        19        23        11

In [4]:
data1 = pd.melt(
    df3.reset_index(),
    id_vars=['index'],
    value_vars=['cotwt.15', 'cotwt.20', 'cotwt.25', 'cotwt.30', 'cotwt.35']
)

data1.columns = ['id', 'treatments', 'value']

data1.head()

   id treatments  value
0   0   cotwt.15      7
1   1   cotwt.15      7
2   2   cotwt.15     15
3   3   cotwt.15     11
4   4   cotwt.15      9

In [5]:
mc = MultiComparison(data1['value'], data1['treatments'])
mcresults = mc.tukeyhsd(0.05)
mcresults.summary()